POST http://localhost:3001/api/restockOrder HTTP/1.1
content-type: application/json

 {
    "issueDate":"2021/11/29 09:33",
    "products": [{"SKUId":12,"description":"a product","price":10.99,"qty":30},
                {"SKUId":180,"description":"another product","price":11.99,"qty":20}],
    "supplierId" : 1,
    "transportNote":{"deliveryDate":"2021/12/29"}
 }

   //"skuItems" : [{"SKUId":12,"rfid":"12345678901234567890123456789016"},{"SKUId":12,"rfid":"12345678901234567890123456789017"}]

###
GET http://localhost:3001/api/restockOrders HTTP/1.1
###
GET http://localhost:3001/api/restockOrders/5 HTTP/1.1
###
GET http://localhost:3001/api/restockOrders/5/returnItems HTTP/1.1
###
PUT  http://localhost:3001/api/restockOrder/6 HTTP/1.1
content-type: application/json

{
    "newState": "DELIVERED"
}
###
PUT  http://localhost:3001/api/restockOrder/6/skuItems HTTP/1.1
content-type: application/json

{
    "skuItems" : [{"SKUId":12,"rfids":"12345678901234567890123456789016"},{"SKUId":12,"rfid":"12345678901234567890123456789017"}]
}
###
PUT  http://localhost:3001/api/restockOrder/6/transportNote HTTP/1.1
content-type: application/json

{
    "transportNote":{"deliveryDate":"2021/12/29"}    
}
###
DELETE http://localhost:3001/api/restockOrder/14 HTTP/1.1
###