POST http://localhost:3001/api/sku HTTP/1.1
content-type: application/json

{
    "description" : "a new sku",
    "weight" : 100,
    "volume" : 50,
    "notes" : "first SKU",
    "price" : 10.99,
    "availableQuantity" : 50
}


###
GET http://localhost:3001/api/skus HTTP/1.1
###
GET http://localhost:3001/api/skus/1 HTTP/1.1
###
PUT  http://localhost:3001/api/sku/1 HTTP/1.1
content-type: application/json

{
    "newDescription" : "newly edited sku",
    "newWeight" : 100,
    "newVolume" : 50,
    "newNotes" : "first SKU",
    "newPrice" : 10.99,
    "newAvailableQuantity" : 50
}


###
PUT  http://localhost:3001/api/sku/1/position HTTP/1.1
content-type: application/json

{
    "position": "800234543412"
}
###
DELETE http://localhost:3001/api/skus/7 HTTP/1.1
###

